upwork:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: upwork-test-504106
      dataset: dev
      threads: 4  
      location: EU
      OPTIONAL_CONFIG: VALUE

    prod:
      type: bigquery
      method: oauth
      project: upwork-test-504106
      dataset: prod
      threads: 4  
      location: EU
      OPTIONAL_CONFIG: VALUE

  target: dev